### ISSUE TITLE
Support new Postmark API requirements

### ISSUE THREAD

**Issue by christaggart** [Webador/SlmMail#155]
Postmark now requires that JSON payloads be sent with as `application/json` instead of a form post as per https://postmarkapp.com/updates/changes-to-email-api-validation-action-may-be-required.

I haven't tested this yet, but should be as simple as calling with $this->client->setEncType('application/json') in PostmarkService's `send()` method.

**Comment by roelvanduijnhoven** [comment]
@christaggart Feel free to contribute a PR that addresses that :).
